# Generated by Django 2.1.5 on 2020-07-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlists',
            name='playlist_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
