# Generated by Django 2.1.5 on 2020-07-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200712_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='playlist_owner',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
